### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#109]
**Describe the solution you'd like**
Allow a user to add as many tags as they want (Strings). A `Set` could be used instead of a `List` as ordering is not required, but it would be useful to find duplicate tags for a particular book.

This change should be a backend only change for now. The user will be able to add a tag via the book page (issue #108  once it is implemented.

**Comment by Jumismo** [comment]
I would like take this issue

**Comment by Jumismo** [comment]
Hi @knjk04 

I would like take this issue.

I will create a attribute Set<String> in Book class.
Also, I can create a attribute Set<Tag> for implement more functionality like a type of tags for example

**Comment by knjk04** [comment]
Thanks!

**Comment by Jumismo** [comment]
Hi @knjk04 

I'm working with the issue to add tags to a book and I have created a new class Tag with the name and a relationship OneToMany but I can do it with relationship ManyToMany for reuse the Tags created for anothers Books

**Comment by knjk04** [comment]
Hi, I've responded to the same question you asked on Gitter. I've pasted my reply here for anyone else who wanted to follow this conversation:

> Thanks for getting in touch. I think many to many is better here
