### ISSUE TITLE
An Author should have a set of books

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#110]
**Describe the solution you'd like**
A `Book` currently has an `Author`, but an `Author` does not contain any books.

The `Author` entity should have a set of books (one-to-many).

A `Set` should be used instead of a `List` as it would be better to find duplicates than have an ordering. 

There should also be a JPA query for retrieving all of the books by particular author (see `PredefinedShelfRepository` for a similar query but on shelves)

**Comment by ranjithmuddana** [comment]
Hi @knjk04 
I would like to contribute to this issue. Please let me know if can help here

**Comment by knjk04** [comment]
Sure, that would be great. Let me know if you need anything

**Comment by knjk04** [comment]
How are you getting on with this issue?

**Comment by jmprathab** [comment]
@knjk04 I can collaborate on this issue. I can start working once you assign me this issue - Just to be sure no one else is working on this.

**Comment by knjk04** [comment]
@jmprathab Thanks, I'll assign you to the issue
