### ISSUE TITLE
Change Project Lombok Maven dependency scope

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#112]
Currently, contributors using Eclipse have to either manually install the Project Lombok Jar or add the dependency into the pom.xml themselves.

Add the Project Lombok Jar so that they don't need to do either.

**Comment by judeibe** [comment]
The Lombok jar is in the dependency, if you have the Lombok plugin in IntelliJ that's all you need. But for Eclipse they can double click the jar that will download when they pull dependencies. 
https://github.com/knjk04/book-project/blob/ccf268b8cded366db38bddd8e7d419d20f0a5b17/pom.xml#L77-L82
https://www.baeldung.com/lombok-ide

**Comment by knjk04** [comment]
Ah, my bad. Thanks for this. I'll close this issue then.

**Comment by knjk04** [comment]
Since the scope is set to `provided`, I couldn't find the jar in the maven dependencies at compile time. I think the scope tag could be removed (defaulting to `compile`)?
