### ISSUE TITLE
Broken Link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by thomasogara** [knjk04/book-project#116]
**Describe the bug**

On line 5 of CONTRIBUTING.md, the link which is titled 'version on the master branch' is broken. When clicked, it will invite most users to fork the repository. This is not the intended behaviour.

**To Reproduce**
1. Go to [CONTRIBUTING.md](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md)
2. Click on the link on line 5 titled 'version on the master branch'.
3. Users with write privileges for the repository will see that a page will load allowing them to edit the file. Those without write privileges will be asked to fork the repo, so that they can edit the file on their own fork of the repo.

**Expected behaviour**

The 'blob' page should open, allowing all users to view the version of CONTRIBUTING.md on the master branch.

**Screenshots**

N/A

**Additional context**

N/A

The bug is just caused by a small typo in the link. Rather than having the link set to https://.../edit/..., the link should be set to https://.../blob/...

- thomas

**Comment by knjk04** [comment]
Thanks for raising this!
