### ISSUE TITLE
Unable to sort by an author's first name

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#118]
**Describe the bug**

A comparator was added so that authors could be compared by an author's first name in the grid.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a shelf
2. See error

**Expected behaviour**

There should be arrows next to the column name to denote that it is sortable.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/86828211-d3d20e00-c08a-11ea-97fd-d6560921e7b2.png)

Note that the title column is sortable (it has the arrows), but the author column is not.

**Additional context**

This was implemented in PR #107

**Comment by pratik-bongale** [comment]
I can try this one out if no one is currently working on it.

**Comment by knjk04** [comment]
Sure, that would be great. Thanks!
