### ISSUE TITLE
Test BookService's save()

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#148]
`save()` in `BookService` contains lots of log statements that could all be replaced by tests. When `save()` is called, the caller should guarantee, for example, that the `Book`, `Author` and shelf to save are not null.

There should also be a simple test to check whether the `bookRepository` count is incremented after a call to save()

**Comment by ashusharmatech** [comment]
Hello,
I will like to work on this.

**Comment by knjk04** [comment]
Thanks!
