### ISSUE TITLE
Behind schedule text still shows when a books target has been met

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#152]
**Describe the bug**

The number of books to read per week on average still shows after switching from a goal that is more than the number of books so read far to a goal that is less than or equal to the number of books read so far.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Go to the reading goal page
3. Click on 'set goal'
4. Select the goal type as 'books'
5. Enter in 8
7. Click on save
8. Click on 'update goal'
9. Set the goal type as 'books'
10. Enter in 4
11. Click on save
12. See error

**Expected behaviour**

The number of books to read per week should not show if the target has been met

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/87582651-998fee80-c6d2-11ea-885d-957b0b568db4.png)

**Additional context**

Manually refreshing the page does fix this, but a refresh should not be needed.

**Comment by pratik-bongale** [comment]
Can you please assign this one to me?

**Comment by knjk04** [comment]
Sure! Before I assign you, are you also happy to write a unit test to ensure that this text does not show when the target has been met?

**Comment by pratik-bongale** [comment]
Yes. I will write a test to ensure that. 
I had a question: Shouldn't there be some validation to restrict users from setting a goal value that they have already achieved? 
i.e `if (haveRead > targetToRead)` then set the input as invalid and ask user to enter a new value higher than `haveRead`?

**Comment by knjk04** [comment]
I think it's best not to have that restriction. Some users may have unknowingly already met their target and are happy with that. If a particular user did want to challenge themselves, they could always set a higher goal later.

However, it's a good idea, so I'll keep it in mind. I'm open to changing my mind, so if the validation you suggested becomes a popular request, then I would be happy to permit it :)

**Comment by tjrelyts** [comment]
Hi I'm working on the PR for #177. I haven't been able to replicate this issue. My goal isn't 5 books however, it has been 2. Either way, I haven't been able to replicate it.

**Comment by pratik-bongale** [comment]
Hi @tjrelyts, I have proposed a fix for this issue in my PR #155. 

To replicate this issue, you need to make sure you have 5 books in your **Read** shelf. You need to set goal higher than 5. save it and then again set goal to a number less than 5.
