### ISSUE TITLE
Book information pop-up window

### ISSUE THREAD

**Issue by jacobdadoun** [knjk04/book-project#153]
**Describe the bug**

Book information pop-up window has text overlapping the fields

**A clear and concise description of what the bug is.**
Hypothesis: Book information pop up window is not wide enough

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'My Books'
2. Click on 'To Read'
3. Select a book

**Expected behaviour**
Either wider window or revised layout

**A clear and concise description of what you expected to happen.**
A clean book information layout

**Comment by knjk04** [comment]
Thanks for this. Could you provide us with the following information:

- A screenshot showing the bug
- The dimensions of your display

Thanks!

**Comment by jacobdadoun** [comment]
You're right. Apologies as I haven't noticed.

**Comment by knjk04** [comment]
No apologies needed :)
