### ISSUE TITLE
Store book edition

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#16]
**Describe the solution you'd like**
Let a user specify which edition of the book they have read.

This should only affect the back-end for now. The `Book` entity should take an `int` that is at least 1. It should store the book edition as a `String`. 

Examples:
- If the edition passed in is 1, the edition stored should be "1st edition"
- If the edition passed in is 2, the edition stored should be "2nd edition"
- If the edition passed in is 3, the edition stored should be "3rd edition"
and so on

**Comment by Jumismo** [comment]
Hi @knjk04
I would like to contribute to this issue.

Design:
- Attribute edition of int type
- Method getTextEdition for print the text. For that, I will take the last digit of the version and I will check if this digit is 1, 2 or 3 for the text.

**Comment by knjk04** [comment]
Thanks! Your approach seems spot on
