### ISSUE TITLE
Filter by author

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#168]
**Is your feature request related to a problem? If so, please describe.**
Currently, books can be only be filtered by book title. However, a user may wish to see all of the books by a particular author. While a user could sort the author column by the author's first name, it may be cumbersome to have to trawl through lots of entries.

**Describe the solution you'd like**

Have a text field that allows a user to enter in the name of the author. This filter should be similar to the existing filter for a book title.

For the time being, only authors in the selected shelf should show. If there are no matching authors, no entries should show.

**Additional context**

The UI will later be modified so that there is a filter button that opens a dialog where a user can see the options for filtering by book title and author (and other filters later on)

**Comment by nagasaichaitanya** [comment]
Hi Kiran, can i take this up. Thanks.

**Comment by knjk04** [comment]
Hi, sure. Thanks!
