### ISSUE TITLE
Only show series position if a book is in a series

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#170]
**Is your feature request related to a problem? If so, please describe.**
The series number 1 is shown in the book grid even when a book is not in a series. 

![image](https://user-images.githubusercontent.com/11173328/87872105-c3d0fd00-c9ad-11ea-84f9-ebe186f3aa9e.png)

**Describe the solution you'd like**
The series form item in `BookForm` should show only if a new 'is in series?' checkbox is ticked (which should be off by default).

The series position will then not be set (so it'll be null), which means that it won't be shown in the book grid

**Comment by amit1307** [comment]
Hello, if this issue is still open may I try it?

**Comment by amit1307** [comment]
Sorry, looks like it's a UI specific work. I thought it's a backend change, please let me know if there is any backend work needed for this issue?

**Comment by knjk04** [comment]
I don't know if you've used Vaadin before, but the frontend is also in Java (no problem if you still don't want to do it).

You can definitely do the backend for this, but I think it'll be easier when the frontend is in place, so I can let you know when that's done if someone only wants to do the frontend

**Comment by amit1307** [comment]
Yes I realised it bit later after posting the comment here, I am happy to do both if you want to assign it to me?

**Comment by knjk04** [comment]
Sure

**Comment by amit1307** [comment]
Hey, I was giving it a try but wasn't sure about the exact issue. The problem description says: `The series number 1 is shown in the book grid even when a book is not in a series`. The proposed solution says: `The series form item in BookForm should show only if a new 'is in series?' checkbox is ticked`

I have below questions:

1. Do we (as in the application) decide or user decides if a book is in a series or not? When I try to add a new book it gives me an option of mentioning if the book being added is part of a series or not. If I add the series number there and even if there are no other books related to the book being added still isn't it correct behaviour to display the series number added by the user for this book?
2. If the app decides about a book being part of series or not then do we need to show the series number on the form and allow user to enter it?
3. Again if it's up to the application to decide how do we decide that?

I am sorry if I have understood the requirement wrong, just clarifying before starting on it.

**Comment by knjk04** [comment]
No, that's absolutely fine. It's good to clarify this before starting:

What we want is a form item with two checkboxes (or radio buttons) so that the user, not the app, decides whether the book is in a series. If the user checks the 'yes' button, then the 'enter series position' field should show.

1. Yes, the behaviour is correct. The user does not have to enter in a series position. However, they might even if the book is in a series. It would be nicer if this was only shown if the book was in a series, hence why we're looking for the user to explicitly state whether the book is in a series.

Hopefully, points 2 and 3 are answered now.

Let us know if you need anything else

**Comment by amit1307** [comment]
Thanks for the detailed explanation, have raised the PR. Since I don't have any experience in Vaadin so please let me know if I missed anything or didn't follow the best practices.

**Comment by knjk04** [comment]
Thanks! I'll review it shortly
