### ISSUE TITLE
Add book review to frontend

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#171]
**Describe the solution you'd like**

The `BookForm` should show have a [text area](https://vaadin.com/components/vaadin-text-area) component for adding a review. Only books that are in the 'read' shelf should have a review. The review field is optional.

The review should not show in the book grid. 

Additional requirements:
- Clear field button
- Placeholder

**Comment by Tom-private** [comment]
Hi, I would like to implement this issue.

My idea for the implementation:
- add a bookReview TextField and bookReviewFormItem to the BookForm
- implement a method to hide / show the field when the predefined shelf is changed (similar to rating)
- add the new bookReview field to the tests in the BookFormTest

Like this:
![image](https://user-images.githubusercontent.com/58065733/91481701-1ce15a00-e8a5-11ea-88f0-646d0dc6ee42.png)

**Comment by knjk04** [comment]
Thanks, that's nearly spot on. There's just a few things that need addressing:

- Could you replace the text field with a text area component (see the link in the issue description)? 
- Could you add the clear button?
- I know this wasn't mentioned in the issue description, but could you make the review field appear as the last field (so after the series check box and number field)?

**Comment by Tom-private** [comment]
Ah, sorry my bad.
Now it looks like this:
![image](https://user-images.githubusercontent.com/58065733/91572183-d47a7880-e946-11ea-8cc8-ad29c97c4ff0.png)
The clear button only appears when a value is set.
![image](https://user-images.githubusercontent.com/58065733/91572921-10154280-e947-11ea-82a9-45d91ea0e3af.png)
This is the same for e.g. the author name. Is that not the expected behavior?

**Comment by knjk04** [comment]
Thanks. Sorry, could you also have the book review field span two columns (let me know if you need a hand with this)?

>  This is the same for e.g. the author name. Is that not the expected behavior?

You're right, I forgot about that.

**Comment by Tom-private** [comment]
I got this:
![image](https://user-images.githubusercontent.com/58065733/91633124-19a1b780-e9e6-11ea-96f3-023b65bca76b.png)
but the current solution looks unpleasant when the form is resized:
![image](https://user-images.githubusercontent.com/58065733/91633158-58d00880-e9e6-11ea-9850-8ce06a1fc4ac.png)

The corresponding code looks like this:
```java
bookReviewFormItem = formLayout.addFormItem(bookReview, "Book review");
bookReview.setWidth("100%");        // without this, the text area is only 1 column wide
bookReview.setMaxWidth("57.7em");        // this is needed to align the text area with the other form items on the right (in full width form)
formLayout.add(bookReviewFormItem, 2);
```
I really do not like the usage of setWidth and setMaxWidth and I we probably agree, that it is bad style, but ```bookReview.getElement().setAttribute("colspan", "2");``` which I found when researching, has no effect, and I couldn't for the life of me figure out why.

**Comment by knjk04** [comment]
Ah, my bad. It didn't look the way I thought it would when it spanned two columns. Could you go back to making it span only one column and then create a PR? Sorry about that
