### ISSUE TITLE
Add a placeholder for the book rating form field

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#175]
![image](https://user-images.githubusercontent.com/11173328/87912441-4ec0fe80-ca65-11ea-9610-77109b7fef93.png)

Add a placeholder (e.g. 'enter a rating') for the rating field in the `BookForm`.

**Comment by tmrd993** [comment]
Can you assign this to me?

**Comment by knjk04** [comment]
Thanks

**Comment by knjk04** [comment]
See #180
