### ISSUE TITLE
User/Role System

### ISSUE THREAD

**Issue by ChFlick** [knjk04/book-project#183]
**Is your feature request related to a problem? If so, please describe.**
Currently, there is only one default user in Spring "in-memory", not loaded from the database.

**Describe the solution you'd like**
The users and their roles should be stored in the database, to enable login, registration (#140) , etc.

**Additional context**
I already started to work on it, based on the MySQL solution, see #61/#169.

**Comment by knjk04** [comment]
Thanks!
