### ISSUE TITLE
Number of pages allow -ve value

### ISSUE THREAD

**Issue by amit1307** [knjk04/book-project#184]
**Describe the bug**

Number of pages allow a -ve value when adding a new book or updating an existing book.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'My Books'
2. Click on 'Add Book.'
3. Enter mandatory fields
4. Enter -1 for 'Number of pages'
5. Click 'Add Book'

**Expected behaviour**

Error message and not allow to add or update book with -ve number of pages

**Comment by knjk04** [comment]
Thanks for this, I'll check this out in the next week or so

**Comment by amit1307** [comment]
Thanks for your response, I can work on this if it's okay?

**Comment by knjk04** [comment]
Before I assign you, I'd like to be able to reproduce this. From memory, I had tested this and thought it was working. I thought the following line should have worked: 

https://github.com/knjk04/book-project/blob/master/src/main/java/com/karankumar/bookproject/ui/book/BookForm.java#L482

But, of course, you may be right and this may be a bug

**Comment by amit1307** [comment]
Sure, I thought (not 100% sure) there might be a validator missing like we have for series position here:

https://github.com/knjk04/book-project/blob/master/src/main/java/com/karankumar/bookproject/ui/book/BookForm.java#L173

**Comment by knjk04** [comment]
I think you're right. Initially, I thought just setting the integer field's minimum value to 1 would work (https://github.com/knjk04/book-project/blob/master/src/main/java/com/karankumar/bookproject/ui/book/BookForm.java#L360), but this bug appears when one enters a negative value, not when one uses the increment and decrement buttons
