### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#186]
**Describe the bug**

After running the app, I see a screen with only some heading text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the app
2. Log in
3. See error

**Expected behaviour**

The login screen should show.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/88363003-61457b80-cd76-11ea-8e64-3420a597f9b8.png)

**Browsers affected**

- Firefox 78.0.2
- Chromium 84.0.4147.89

**Comment by YBrecher** [comment]
Has this bug been dealt with because I just pulled the latest version of the code and I'm not having this issue. I tried it on chrome and firefox and it worked fine on both.

**Comment by knjk04** [comment]
Not for me, so this might just be something I am, or few people are, facing. Thanks for letting us know that it worked for you, though! That's good to know.

**Comment by knjk04** [comment]
Re-cloned a second time and this time it's fine.
