### ISSUE TITLE
Split BooksInShelfView

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#197]
The Javadoc class comment for the `BooksInShelfView` class:

>  Contains a @see BookForm and a grid containing a list of books in a given shelf.

This clearly violates the Single responsibility principle, so this class could be refactored for easier maintenance in the future.

**Comment by kaansonmezoz** [comment]
I'd like take this issue on me, If no one's looking into 🙂

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by kaansonmezoz** [comment]
Could you review my [PR](https://github.com/knjk04/book-project/pull/203) when you are free ? :)

**Comment by knjk04** [comment]
Sure
