### ISSUE TITLE
Change the way genres are displayed

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#20]
**Is your feature request related to a problem? If so, please describe.**
It's strange to see the genre in uppercase and for there to be underscores (as in the enum) in the new book form and the shelf grid.

**Describe the solution you'd like**
- Every genre to be displayed in lower case
- Spaces, not underscores, between words

For example, `SCIENCE_FICTION` should be `Science fiction` and, as a special case, `NON_FICTION` should be `Non-fiction`.

**Additional context**
Screenshot:
![genres](https://user-images.githubusercontent.com/11173328/82047873-771a2e80-96ab-11ea-8768-54c06419983e.png)

**Comment by tmrd993** [comment]
I created a pull request for this

https://github.com/knjk04/book-project/pull/27

**Comment by knjk04** [comment]
Thanks!
