### ISSUE TITLE
Rapidly hitting "Add Book" adds multiple copies of the same book to the shelf

### ISSUE THREAD

**Issue by tmrd993** [knjk04/book-project#200]
**Describe the bug**

Rapidly hitting the "Add Book" button when adding a book to a shelf causes the book to appear multiple times on the shelf.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to My Books
2. Click on Add Books
3. Fill out form
4. Rapidly click on "Add Book"

**Expected behaviour**

A filled form should lead to a single book.

**Comment by tmrd993** [comment]
Disabling the save button after a click resolves this issue. I already fixed it, just need to do a PR if that is ok with you.

**Comment by knjk04** [comment]
Thanks for bringing this up. This is strange because for me, the book form dialog closes after 'add button' is clicked. I'll look into this further shortly

**Comment by tmrd993** [comment]
Just to be clear, are you hitting the "Add Book" button multiple times before the dialog closes? It's definitely possible to hit it more than once before it closes, which fires N events for N clicks which adds N books to the shelf.
Here is a gif where I click 4 times. Take a look at the logs to see what I am talking about.

![rapidclicktest](https://user-images.githubusercontent.com/47194464/89274782-aeaccd00-d641-11ea-9ba6-8b581e8ab27c.gif)

**Comment by knjk04** [comment]
I've tried pressing the add button multiple times just now, but it still only saves once for me. However, I can see from your gif the issue, so I'll assign you to it.

Perhaps it's also worth ensuring the dialog actually closes straight away after pressing the button?
