### ISSUE TITLE
Add (already designed) favicon

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#210]
**Describe the solution you'd like**
Add the [16x16 designed favicon](https://github.com/knjk04/book-project/issues/34#issuecomment-669252059) to the app.

**Comment by josephkenny** [comment]
May I work on this?

Thanks!

**Comment by knjk04** [comment]
Sure, thanks again for all of your help!

**Comment by knjk04** [comment]
Let us know if you need a different size. For some reason, I came across Vaadin needing a 500x500 image, not the standard 16x16. If that is the case, I can request our designer to create it/do it myself.
