### ISSUE TITLE
Add email regular expression

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#231]
In the `User` class, we have the following field:

```java
    @NotNull
    @NotEmpty
    private String email;
```

Add a regular expression pattern that checks to ensure that only valid email addresses are permitted.

**Additional context**

As this is a new feature, tests to ensure your regular expression works are required.

**Comment by inhundreds** [comment]
Hello, I'd like to work on this. 

There are a lot of possible regexp that can be applied for email address validation. I plan to use the one here: https://owasp.org/www-community/OWASP_Validation_Regex_Repository

Let me know what do you think about it.
Thanks,
Diego

**Comment by knjk04** [comment]
Hello, 

It looks good to me from a quick glance. I'll assign you to the issue. 

Let us know if you need any help over Gitter.

Thanks!
