### ISSUE TITLE
Add Java to Docker container

### ISSUE THREAD

**Issue by gm7y8** [knjk04/book-project#260]
**Is your feature request related to a problem? If so, please describe.**
Dockerize the application, so we can avoid environment setup for testing and using the application 

**Describe the solution you'd like**
use the minimal alpine java image to run the spring boot application 

**Additional context**

**Comment by gm7y8** [comment]
I can implement this enhancement.

**Comment by knjk04** [comment]
Thanks for getting in touch and offering to work on this! This would definitely be useful. 

Is this issue the same as #160?

**Comment by gm7y8** [comment]
Yes, looks similar.

**Comment by knjk04** [comment]
Sure, thanks

**Comment by gm7y8** [comment]
@knjk04 Here is enhancement.. can you review it?

**Comment by knjk04** [comment]
Sure, I'll review it shortly

**Comment by gm7y8** [comment]
@knjk04 actually a couple of tests are failing in master branch.. you can run mvn command with -DskipTests to test this

**Comment by knjk04** [comment]
What tests are failing for you? For me, the build fails because we haven't set a goal yet. In IntelliJ, I ran the tests and they all pass.

**Comment by gm7y8** [comment]
@knjk04  you can ignore my comment.. we should be good.
