### ISSUE TITLE
Consider password strength for password security

### ISSUE THREAD

**Issue by ChFlick** [knjk04/book-project#262]
Currently password "strength" is implemented via a valid regex so that it consists of 8 characters with alphanumeric chars and special characters, but I think using a password strength algorithm is much better for the user experience.

I've heard good things about https://github.com/nulab/zxcvbn4j.

Edit: See also https://stackoverflow.com/questions/48345922/reference-password-validation

**Comment by knjk04** [comment]
It would also be good if we could show a password strength bar.

**Comment by tmrd993** [comment]
I didn't replace the regex yet but I played around with vaadin components and I think the vaadin progress bar (free component) looks pretty good. Here is a working gif.
![passstrenindicator](https://user-images.githubusercontent.com/47194464/91032774-bd641f80-e602-11ea-86d0-837715f504a3.gif)

I think it looks quite nice as it's in line with the design of the other vaadin components. I use the library above (zxcvbn4j) to calculate a score whenever the user changes the password field and update the value and color of the progress bar.

The value range of the progress bar goes from 0 to 1.0. I currently have it set up like this 
`passwordStrengthMeter.setValue((score) / 4.0);`

Which gives us no value (empty bar) for a score of zero or 1 (red bar), 50% for a fair score (orange bar), 75% for a strong score and 100% for a very strong score (green bar). 

What do you think?

**Comment by knjk04** [comment]
It looks really good! Could you also add some text underneath the progress bar to represent the strength (e.g. 'weak', 'strong', etc.)

**Comment by tmrd993** [comment]
![passstrenindicator](https://user-images.githubusercontent.com/47194464/91165990-ed2e2880-e6d1-11ea-9a04-2731faac4540.gif)

I already replaced the regex with a custom constraint, the way it works now is, that the password is valid if the Zxcvbn algorithm returns a 3. Which is a "Strong" password. This can be changed very easily though, we can also add other restrictions on top of zxcvbn like minimum amount of characters. I also changed the progress bar. It has 5 stages now for all values of zxcvbn (weak, fair, good, strong, very strong). I can explain what I did in detail if you're okay with the gif above.

**Comment by knjk04** [comment]
That's great, thanks. For the 'strong' state, what do you think about changing the colour of the bar to a lighter shade of green?

**Comment by tmrd993** [comment]
Sure. These are the colors I am currently using.
![passstrenindicator](https://user-images.githubusercontent.com/47194464/91183462-cda3f980-e6eb-11ea-843c-6515fdd9931b.gif)

**Comment by tmrd993** [comment]
Cool, no problem.

What about the tests though? Right now they should all pass but it's easily possible to create a strong password using only lowercase/uppercase letters. Likewise, it should be possible to create a strong password without any digits or special characters, or one with less than 8 characters. I think those tests can be removed and we can instead test for weak, fair and good passwords according to the password strength algorithm.

**Comment by knjk04** [comment]
Do you know what the minimum number of characters is for a strong password? I thought it would be good to require at least eight characters to make it harder for someone to use brute force since the size of search space increases.

**Comment by ChFlick** [comment]
> Do you know what the minimum number of characters is for a strong password? I thought it would be good to require at least eight characters to make it harder for someone to use brute force since the size of search space increases.

I don't know how the number of characters are processed with zxcvbn, but internally it does calculate a duration of how long it would take an attacker to brute-force the password, therefore I don't think a hard limitation from out side is needed.

For example:
password: | Tr0ub4dour&3
-- | --
guesses_log10: | 7.28008
score: | 2 / 4
function runtime (ms): | 1
guess times:
100 / hour: | 21 years | (throttled online attack)
10  / second: | 22 days | (unthrottled online attack)
10k / second: | 32 minutes | (offline attack, slow hash, many cores)
10B / second: | less than a second | (offline attack, fast hash, many cores)


> That's a good point you made on being able to make a strong password with only letters. I'm thinking that it may be hard for a user to understand what constitutes a strong password (e.g. if they write a password that is deemed weak). What do you think about changing the requirement of using special characters and digits from a requirement to a suggestion?

Thats a good option IMO. Though I think that with the "password strength bar" it feels quite natural to create a strong password, as you see how the strength develops as you type.
We could also use the suggestions output from zxcvbn, which indicates how a password could be improved.

The suggestions zxcvbn outputs for the example above:
- Add another word or two. Uncommon words are better.
- Capitalization doesn't help very much
- Predictable substitutions like '@' instead of 'a' don't help very much

**Comment by tmrd993** [comment]
> 
> 
> Do you know what the minimum number of characters is for a strong password? I thought it would be good to require at least eight characters to make it harder for someone to use brute force since the size of search space increases.

I couldn't find any information about that but I did some testing, the minimum number of characters for strong passwords seems to be 9. I didn't manage to make a strong password using fewer characters.

> That's a good point you made on being able to make a strong password with only letters. I'm thinking that it may be hard for a user to understand what constitutes a strong password (e.g. if they write a password that is deemed weak). What do you think about changing the requirement of using special characters and digits from a requirement to a suggestion?
> 
> I haven't looked at your PR yet, but it seems from your gif that we're only now accepting strong passwords, which is nice.

There are no requirements right now beyond a strong password strength. The information displayed in red is a suggestion that gets displayed if the user chooses a password that isn't strong or very strong.

**Comment by knjk04** [comment]
@ChFlick Thanks a lot, that makes sense (I like the xkcd reference!). It's good to know what zxcbn can offer suggestions on how to improve the password, rather than us having to make general suggestions.

@tmrd993 My bad. I'm thinking of the current implementation. That's fine. We can make suggestions on how to create a strong password a separate issue.
