### ISSUE TITLE
Add book form errors

### ISSUE THREAD

**Issue by amit1307** [knjk04/book-project#274]
**Describe the bug**

Clicking on Add book button opens the new form with all the form validations errors. This happens even before user has entered anything in the form.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  My books
2. Select To read shelf
3. Pick any book, update anything and save
4. Click on Add book and the new form opens with lots of form validation errors

**Expected behaviour**

A new form should never show any validation errors. The validation errors should appear only when cursor is moved out without valid value in any of the form fields.

**Screenshots**

![image](https://user-images.githubusercontent.com/23420222/91548379-31613900-e91d-11ea-8569-4a56b7186a7f.png)

**Comment by knjk04** [comment]
Thanks for this. This seems to to be the same issue as #54?

**Comment by amit1307** [comment]
Oh yes, sorry my bad. Closing this one.
