### ISSUE TITLE
Add Book dialog needs formatting improvements

### ISSUE THREAD

**Issue by MikeLowrie** [knjk04/book-project#275]
Depending on the browser window size of the user, the Add Book dialog can have overlapping details and make sections difficult to read and interact with. Shown below is an instance I had in Firefox where, rather than using fullscreen, I reduced my window size and encountered the object overlap. For reference, my monitor is 1920 x 1080, and the screenshot shows my browser at roughly 60% the width of the monitor.

![image](https://user-images.githubusercontent.com/25354159/91564873-4b941a80-e90f-11ea-9de9-cb8fbc409ea2.png)

What is good is that the objects will form a single column if the browser's width is reduced enough, preventing object overlap. However, it would be better to either keep items in a single column for more width, or simply push items off to the right of the dialog and have users scroll right-left to interact with certain components.

**Comment by knjk04** [comment]
Thanks for bringing this up. Is seems this is the same issue as #57. Could you confirm this?

**Comment by MikeLowrie** [comment]
Yes it is, my apologies for missing that.

**Comment by knjk04** [comment]
No matter
