### ISSUE TITLE
Improve design of 'add shelf' form

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#292]
**Is your feature request related to a problem? If so, please describe.**

![image](https://user-images.githubusercontent.com/11173328/91884707-73bcaa00-ec7e-11ea-94dd-ca9fb118837d.png)

The add shelf form looks quite bad. The 'save shelf' button is unnecessarily big, the dialog is also unnecessarily big and there doesn't need to be a scrollbar.

**Describe the solution you'd like**
Improve the design by addressing the above concerns.

**Additional context**

From @TomGilke2468: 
> As far as my research told me, a class can only be set to the overlay via JavaScript (like find all overlay-elements and add class "bookFormOverlay" to the one containing the bookForm and class "addShelfOverlay" to the one containing the addShelfForm).

**Comment by Tom-private** [comment]
Idea on how to solve the "we cannot differentiate between the overlays" issue:
JavaScript can be executed by vaadin (https://vaadin.com/docs/v10/flow/advanced/tutorial-execute-javascript.html), so I would add some JavaScript to the constructor of the BooksInShelfView (after initialization of the bookForm and the addShelf form) which finds the overlay objects and adds classes to them.
These classes can then be used to style the forms differently.

I would like to work on this issue.

**Comment by knjk04** [comment]
Thanks, that sounds great! I'll assign you to the issue.
