### ISSUE TITLE
Design a favicon

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#34]
Design a favicon to be used for the site. 

Ideally, if someone sees the icon, they should be able to reasonably extrapolate that the website is book-related.

2 files formats needed: 
- png 
- ico

**Update**: please ensure that the favicon is of your own making or it has an appropriate open source license. If there's a license, please let us know so that we can attribute the source.

**Comment by josephkenny** [comment]
If no one wants to design one we could use from here: https://www.flaticon.com/search?word=book

And here's a favicon generator website: https://favicon.io

**Comment by knjk04** [comment]
Thanks for this. 

I've used flaticon.com and a favicon generator before, but I was hoping for a tailor-made one. However, that's still definitely an option.

**Comment by Onyx-Obelisk** [comment]
![Book_Project_Favicon](https://user-images.githubusercontent.com/38171859/88582581-f49fda80-d01c-11ea-9581-b7abb04aa087.png)
[Book_Project_Favicon.ico.zip](https://github.com/knjk04/book-project/files/4984029/Book_Project_Favicon.ico.zip)

Used colors from ReadMe Banner.
Designed in Inkscape.
Used www.convertico.com for PNG to ICO conversion.

_No attribution necessary._

**Please provide feedback.**

**Comment by knjk04** [comment]
Thanks a lot for this! 

![image](https://user-images.githubusercontent.com/11173328/88763880-cf6db200-d16b-11ea-9a9d-f7fb463fe350.png)

Are both the yellows block on the left and right meant to be books?

**Comment by Onyx-Obelisk** [comment]
The image was designed with the intention * that: 
**Blue** represents the **Book Shell**
**Beige** represents the **Paper** and **Cover Image** **

_**Abstraction is a design principle, so it is fine if you understood the Favicon differently.
*Without the Cover Image, I felt it wasn't clear that it was a Book._

**If you have any modifications or additional requests please let me know.**

**Comment by knjk04** [comment]
That's quite interesting. However, I think it would better suit our requirements if someone could reasonably extrapolate from the favicon alone that this is app is book-related (I still can't see the book).

I like how you used our banner colours. From a design perspective, what do you think of something like the following?

![book-project-favicon-new](https://user-images.githubusercontent.com/11173328/88808690-1af38080-d1ab-11ea-80ed-eb9cc7937f18.png)

I was thinking that something like this, perhaps with the books having rounded corners, retains the simplicity while better representing our app.

**Comment by Onyx-Obelisk** [comment]
Thank you for your feedback and suggestions.
I have attempted to capture your idea, as I understood it.


![Book_Project_Favicon_02](https://user-images.githubusercontent.com/38171859/88840987-4d9d7900-d1ab-11ea-91f4-9db4713221d4.png)

![Book_Project_Favicon_02_L](https://user-images.githubusercontent.com/38171859/88840966-44aca780-d1ab-11ea-9448-766d4a9c2c27.png)


Used colors from ReadMe Banner.
Designed in Inkscape.

_No attribution necessary._

**Blue** represents the **Book Shelf**
**Beige** represents the **Book Side Cover**

From my understanding a Favicon is generally 16 by 16 Px in size, resulting in considerably less detail and a poorer quality image when viewed enlarged instead of at the intended size. 

I would also be interested if you would like an attempt using assets from the icon resources mentioned above, tweaked and designed specifically for your project.

**Please advise how you would like future attempts submitted.**

**Comment by knjk04** [comment]
Thanks for this.

I'm really sorry, I should have checked the size at 16x16. Unfortunately, it seems that it may be very hard to actually see the favicon represents books at that size. I'm thinking that we should redesign this? What do you think?

I don't want to abandon what you have designed so far. We were looking to change the logo (made using Canva) to something 'homemade', so we could definitely still use what you've made so far. For the logo, I like the idea of leaning books. I think the corners are rounded a bit too much (something like this [logo](https://github.com/knjk04/Bookshelf/blob/master/repoMedia/bookshelf_icon_512.png) is better, in my opinion). While I think the logo should be as simple as possible while still looking good, I think the logo linked is quite nice in terms of colours. It's also clear where the shelf is. Would you mind playing around with the colours to something a little snazzier (which I appreciate is vague!)? With the logo you designed, it isn't clear to me (and perhaps others) that the blue represents the book shelf.

Future attempts for the favicon are fine to be submitted here as a zip and a preview in your comment.

For the logo, could you submit a preview and a zip on the new [logo](https://github.com/knjk04/book-project/issues/195) issue I just made?

Thanks a lot!

**Comment by Onyx-Obelisk** [comment]
Based on your feedback in the [Logo Issue](https://github.com/knjk04/book-project/issues/195).

![Book_Favicon_011](https://user-images.githubusercontent.com/38171859/89429526-a8832300-d70b-11ea-985f-0f5a07451630.png)
[Book_Favicon_16.ico.zip](https://github.com/knjk04/book-project/files/5029242/Book_Favicon_011.ico.zip)
[Book_Favicon_3500.ico.zip](https://github.com/knjk04/book-project/files/5029244/Book_Favicon_012.ico.zip)

Used Colors from Material Design Palette.
Designed in Inkscape.
Used www.convertico.com for PNG to ICO conversion.

No attribution necessary.

This is the same 3500 by 3500 pixel graphic, scaled down to 16 by 16 pixels.
For the **ICO file**, I have included _**both**_ the _**3500**_ and _**16**_ pixel versions, as I figure you can use both.


**Please provide feedback.**

**Comment by knjk04** [comment]
Thanks a lot, the favicon looks great!

I know you said no attribution necessary, but we'd be happy to attribute you. Would you mind if we link to your GitHub profile (or somewhere else of your choosing) in our README?

**Comment by Onyx-Obelisk** [comment]
Thank you for your feedback.

**No attribution necessary.**

Please keep me in mind for future design related issues, as I am glad to assist where I can.

**Comment by knjk04** [comment]
Thanks for all of your help.

What would be the best way to contact you if we have new design-related issues? I can only mention people on unassigned issues if they have committed to the project? I don't think you're in our Gitter room
