### ISSUE TITLE
Use Checkstyle for style guide violations

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#38]
Automate checking for style guide violations on all incoming pull requests.

Checkstyle should be configured to adhere to our style guide (a modified version of Google's). This should then be able to be executed from Maven (e.g. run checkstyle from Maven).

The work for this branch should be off the travis branch.

**Comment by judeibe** [comment]
I saw that there was a bot that was somewhat enforcing this. If this issue is still needed I can work on it.

**Comment by knjk04** [comment]
Thanks, @judeibe! That would be great. I've disabled the Sider bot for now because a custom checkstyle configuration file (tailored to this repository's style guide rather than using Sun or Google's verbatim) is needed. 

If you could make the configuration file, then that would be much appreciated.

**Comment by judeibe** [comment]
I have the checkstyle to give an error on a failed check.
` <property name="severity" value="error"/>`
This will cause an otherwise passing build to fail.
Should this just be warning?

**Comment by knjk04** [comment]
Yes, I think a warning would be better. Thanks!
