### ISSUE TITLE
Form labels overlapping

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#57]
**Describe the bug**

At lower resolutions, the form labels overlap.

**Expected behaviour**

The form should adapt to smaller resolutions.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/85194285-265aae80-b2c5-11ea-91a6-c64149017673.png)

**Additional context**

Not an issue on 2560x1440 displays, but it is an issue on 1920x1080 displays.

**Comment by knjk04** [comment]
Notes:

The fields are given a minimum fixed width in `BookForm.java`

```java
for (HasSize h : components) {
    h.setMinWidth("23em");
}
```

The dialog is set to consume 50% of the screen in `frontend/styles/vaadin-dialog-overlay-styles.css`:
```css
[part="overlay"]{
    width:50%;
}
```

If the minimum size is removed and the dialog width is made larger (e.g. 80%), this is then fine on 1920x1080p displays, but it could be made nicer on smaller devices, such as phones (I've tried the iPhones via Firefox inspector).

Also, the form should be centred within the dialog. I've tried doing this via a `FlexLayout`, but to no avail.

Ideally, the width of the form and the dialog would adapt based on the screen's resolution.
```

**Comment by knjk04** [comment]
This has now been fixed for 1920x1080p displays by increasing the dialog width, but it is still an issue for smaller resolution displays, such as that on mobile devices. A more robust solution that dynamically adjusts the size based on the available space is still needed.

**Comment by Tom-private** [comment]
```java
formLayout.setResponsiveSteps(
                new FormLayout.ResponsiveStep("0", 1),
                new FormLayout.ResponsiveStep("62em", 2)
        );
```
would fix the issue with overlapping.

However, because all inputs are aligned to the left, the form looks really strange, when it is not quite wide enough to have 2 columns.
I have no experience with using vaadin so until now my trial and error approach to align the items to the center did not bring any success.

**Comment by Tom-private** [comment]
Would it be ok for you, if the form would have a fixed width based on the media width? That could also solve the problem with the centering.

**Comment by knjk04** [comment]
> Would it be ok for you, if the form would have a fixed width based on the media width? 

That should be fine. I was thinking of the same thing. 

> Edit: I just saw, that there is already an assignee. Sorry, I missed that.

No, that's fine. I've been busy recently, so I haven't had a chance to start working on this. Would you be interested in picking this issue up?

**Comment by Tom-private** [comment]
Yes, I can do that.
But I can not promise you that I will be able to solve all problems. For widths >=470px I have a solution, but everything below that is very hard, because ```h.setMinWidth("23em");``` has to be overridden with css and currently I can not get a grip ob these input-fields.

What about tests for the responsiveness? (Currently, I have no idea how to approach them so that would involve a lot of research.)

**Comment by knjk04** [comment]
If it helps, we could add a class name for all of the form field components (`.addClassName("foo")`) and then change the minimum width in CSS accordingly. 

Otherwise, that's fine for now. 

> What about tests for the responsiveness? (Currently, I have no idea how to approach them so that would involve a lot of research.)

It's a good suggestion, but I also don't yet know how to go even go about them.
