### ISSUE TITLE
Verify date finished reading is after date started

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#6]
Verify date finished reading is after date started if both fields are filled (they are both optional).

Something like: 
```java
dateStartedReading.getValue().isBefore(dateFinishedReading.getValue());
```

Branch to merge into: [master](https://github.com/knjk04/book-project)

**Comment by knjk04** [comment]
Also, the date finished should not be in the future (i.e. after today's date).

**Comment by sakthivigneshkumar** [comment]
@knjk04 Can i work on this task? Please let me know. This would be my first issue.

**Comment by knjk04** [comment]
Absolutely! Thanks! Let me know if you need anything

**Comment by sakthivigneshkumar** [comment]
Thanks! Working on it.

**Comment by sakthivigneshkumar** [comment]
@knjk04  I have done the changes and created PR. Please check and let me know in case of any concern.

**Comment by knjk04** [comment]
Thanks again!
