### ISSUE TITLE
Replace H2 with MySQL

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#61]

**Comment by rushilp2311** [comment]
Hi, I would like to be assigned to this issue

**Comment by knjk04** [comment]
Sure, that would be great. Thanks!

**Comment by rushilp2311** [comment]
Hey @knjk04 is MySQL compulsory. Can we use postgres instead?

**Comment by knjk04** [comment]
Hey, I'm open to discussing whether to use Postgres vs MySQL. Why do you think Postgres is more suitable for this project?

**Comment by rushilp2311** [comment]
Postgres is a little bit advanced than MySql. 
We can choose either of them.
Check the[ link](https://blog.panoply.io/postgresql-vs.-mysql) you will have a better understanding

**Comment by knjk04** [comment]
Let's go with MySQL

**Comment by knjk04** [comment]
How are you getting on with this issue?

**Comment by knjk04** [comment]
@rushilp2311 As you've unassigned yourself from the issue, I'm going to assume that you no longer wish to work on the issue.

**Comment by ChFlick** [comment]
Hey, if you're not yet working on it, I could do it.

**Comment by knjk04** [comment]
Sure, I haven't started this yet.
