### ISSUE TITLE
Add book review

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#67]
**Describe the solution you'd like**
Store a book review in the `Book` entity class. This should be an optional field (i.e. it should not have a @NotNull annotation). Add getters and setters.

**Additional context**
This should only affect the backend for now (i.e. there should not yet be a way to add a review via the frontend).

For simplicity's sake, this should only be able to store of the text of the review and not any related metadata (e.g. date of when the review was added or last modified)

**Comment by nagasaichaitanya** [comment]
Hi, can you assign me this. Thanks!!

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by nagasaichaitanya** [comment]
Hi @knjk04  update on my Task Sry could not do much in previous weeks as i was bit busy. Hopefully will be doing something in coming days. Thanks!!

**Comment by knjk04** [comment]
No problem, thanks for letting us know!

**Comment by nagasaichaitanya** [comment]
Hi, one question. I think this is all i had to do. Just add a field ?. Setters and getters are taken care of lombok i assume.  

![image](https://user-images.githubusercontent.com/3137947/87868573-89f4fc00-c997-11ea-9368-bcf1e4fedd90.png)

**Comment by knjk04** [comment]
Yes, it's just the field. Thanks

**Comment by knjk04** [comment]
Actually, you may also want to make add some fake reviews in `populateBookRepository()` in the `PredefinedShelfService`

**Comment by nagasaichaitanya** [comment]
Ok will do it. 
one more wanted to share something which i started using recently is about semantic commit message. 
https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716.  
This will help you to generate release notes easily. 
Just wanted to exchange ideas so that we can improve each others skills :)

**Comment by knjk04** [comment]
Thanks for this!
