### ISSUE TITLE
Add 'book recommended by'

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#69]
**Describe the solution you'd like**
Add a String that can store the name of a person. The field should be called something like `bookRecommendedBy` 

**Additional context**
For now, only the name of one person who recommended the book will be stored. 

If the String field is already not empty when the setter is invoked, it does not matter whether the call to the setter replaces this value or does nothing as this may be changed later, and will be handled by the frontend.

For the time being, this patch should only affect the backend. In other words, there should not yet be a way to add who the book was recommended by on the frontend. 

Update: add missing "not yet be" to the final sentence

**Comment by LouisJHC** [comment]
Hi, I would like to work on this issue. Just confirming, by the last two sentences, we would want: 
1. Add the String field to the Book class (thus the name of the recommender can be stored in the DB) on the back-end.
2. An ability to add the recommender of the book (I assume it can be left empty if there is none) on the front-end.

Is this correct?

**Comment by knjk04** [comment]
Hi,

Thanks for raising this. I made a typo, I should have said: "For the time being, this patch should only affect the backend. In other words, there should be **not yet be** a way to add who the book was recommended by on the frontend.". So we only want the `Book` entity changed to include this new field and some dummy data added into the `BookService`.

I hope this clarifies things. Let me know if you need anything else :)

**Comment by LouisJHC** [comment]
Thanks! A question, what do you mean by adding dummy data to the `BookService` class? I see a relevant method to `booksRecommendedBy` field inside `BookSerivice` would be the `save` method, are you referring to adding lines of code into this method?

**Comment by knjk04** [comment]
Sorry, that's another mistake. I should have said dummy data should be added to the `PredefinedShelfService` class.

In the `PredefinedShelfService`, there's a `populateTestData` method that contains some test (or dummy) data. This is where you should set a value for the `bookRecommendedBy` field

**Comment by LouisJHC** [comment]
That's okay :) I got it now.

My approach would be:
1. Add the `bookRecommendedBy` field in the `Book` class. 
2. In the `populateTestData` method inside `PredefinedShelfService` class, I would have sample strings of names (e.g. "John", "Chrstina, etc) in a List form, pick one of the strings out randomly every time the application starts running, and set the `bookRecommendedBy` field with the corresponding name for the book instance.

Would you be okay with this?

**Comment by knjk04** [comment]
That would be great, thanks
