### ISSUE TITLE
Add a 'did not finish' predefined shelf

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#70]
**Describe the solution you'd like**
Add a 'Did not finish' shelf as a predefined shelf in the `PredefinedShelf` entity.

**Additional context**

For now, this should only be a backend change (unless you're happy to work with Vaadin)

**Comment by smoczy123** [comment]
Hi, you can assign this issue to me.

**Comment by knjk04** [comment]
Sure & thanks!

**Comment by smoczy123** [comment]
What columns should show up after did not finish shelf was selected? Title, genre, author, start date and number of pages for sure, but what else? Rating?

**Comment by knjk04** [comment]
Good question! Just the ones you mentioned without rating

**Comment by smoczy123** [comment]
#72
