### ISSUE TITLE
Add pages read field for 'did not finish' shelf

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#73]
**Describe the solution you'd like**
If the 'did not finish' shelf is selected, the grid should show a `pagesRead` field.

**Additional context**
- The `Book` entity needs a new field
- The `pagesRead` field should only be shown if the 'did not finish' shelf is selected.

For the time being, any shelf could have this new `pagesRead` field, but it won't be shown. Later, the code needs to be modified so that only a `DidNotFinishShelf` (which will probably need to be a new class) has this property. If you want, you can make this change as part of this patch.

**Comment by ernesto-tapia** [comment]
Hi, I would like to work on this issue

**Comment by knjk04** [comment]
Sure. Thanks!

**Comment by knjk04** [comment]
@ernesto-tapia How are you getting on with this issue?

**Comment by knjk04** [comment]
@ernesto-tapia We haven't heard back from you in a while, so we've marked the issue as stale. If we don't hear back from you within another 7 days, we will unassign you from the issue so that we can reassign it to someone else.

If you need more time or any help, just let us know.

**Comment by YBrecher** [comment]
Can I be assigned to this issue?

**Comment by knjk04** [comment]
Sure & thanks!
