### ISSUE TITLE
Replace dark mode button with Web Component switch

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#78]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11173328/85584501-1b8e7980-b637-11ea-91cc-a67fb8defaa8.png)

Replace the dark theme toggle button (see above) in the settings page (see `SettingsView.java`) with a [Paper Toggle element](https://vaadin.com/directory/component/polymerelementspaper-toggle-button/overview) 

The functionality should stay the same. When the switch is turned on, dark theme should be enabled. Otherwise, it should not.

**Additional context**

Useful resources:
- [Java API for a web component](https://vaadin.com/docs/v14/flow/web-components/creating-java-api-for-a-web-component.html) 
- [Integrating a web component](https://vaadin.com/docs/v14/flow/web-components/integrating-a-web-component.html)
- [Example project](https://vaadin.com/start/lts/component)

**Comment by YBrecher** [comment]
Can I be assigned to this issue?

**Comment by knjk04** [comment]
Thanks! Let us know if you need a hand
