### ISSUE TITLE
Add date formatting preferences

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#85]
**Is your feature request related to a problem? If so, please describe.**
Current formatting of DD-MM-YYYY may not be suitable for people in places like the USA

**Describe the solution you'd like**
In the settings page, let users toggle (two radio buttons may be good here) between DD-MM-YYYY and MM-DD-YYYY.

**Additional context**
One possible implementation could be to store the preferences in a property based map (see the [Javadoc](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html) and [tutorial](https://docs.oracle.com/javase/tutorial/essential/environment/properties.html) page)

**Comment by knjk04** [comment]
Blocked until issue #84 is implemented

**Comment by knjk04** [comment]
This is still needed for setting the date in the form

**Comment by eklecky** [comment]
Hi can I be assigned to this?

**Comment by knjk04** [comment]
Sure. Thanks!

**Comment by knjk04** [comment]
How are you getting on with this issue?

**Comment by eklecky** [comment]
I'm just trying to figure out how best to solve the issue.

**Comment by knjk04** [comment]
No problem, I'm just checking up as per our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).

Let us know if you need a hand :)

**Comment by knjk04** [comment]
Since the books in shelf grid uses the unambiguous MMM/DD/YYYY format, and the 'add book' form uses the format that matches the user's locale, we don't need a user to set their date formatting preference. We can safely assume that they will be happy with the formatted date based on their locale.
