### ISSUE TITLE
PredefinedShelfTests fail when run collectively

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#88]
**Describe the bug**

When all of the tests run, the `PredefinedShelfTests` fail. If the `PredefinedShelfTests` are run separately, they pass.

**To Reproduce**
Steps to reproduce the behaviour:
1. Right click on the `com.karankumar.bookproject` folder under `test/java`
2. Click on run
3. See error
4. Right click on `PredefinedShelfTests`
5. See that it passes.

**Expected behaviour**

All tests should pass irrespective of whether are run together or individually.

**Additional context**

The tests pass on Travis CI.

**Comment by judeibe** [comment]
Can you assign me this story

**Comment by knjk04** [comment]
Thanks!
