### ISSUE TITLE
Reset all shelves

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#92]
**Describe the solution you'd like**
Delete all of the books in every shelf.

A reset button should be in the settings page. When this button is pressed, a [dialog window](https://vaadin.com/components/vaadin-dialog) should appear asking the user to confirm and informing the user that this action is irreversible.

A test is also required (checking whether all books are actually deleted).

**Comment by knjk04** [comment]
Blocked by issue #18

**Comment by jacobdadoun** [comment]
Hello. May I help you on this issue?

**Comment by knjk04** [comment]
Sure, I've assigned you to the issue.

Please note that I've also edited the issue description to include a test (as per the contributing document).
