### ISSUE TITLE
Grid not updating after searching for query

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#93]
**Describe the bug**

After filtering by a book title, the book shows as expected. However, if the shelf to show is changed, the book still shows, and the grid columns change.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the 'read' shelf
2. Search for 'hob'
3. Switch to a different shelf

**Expected behaviour**

After switching to a different shelf (step 3), the filter query should no longer apply. The text in the filer box should clear.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/85725210-d0cf3900-b6ec-11ea-8774-f257d0ef4bf7.png)
Note that 'The Hobbit' is in the 'read' shelf.

![image](https://user-images.githubusercontent.com/11173328/85724951-95cd0580-b6ec-11ea-99de-7f007a690f0c.png)
'The Hobbit' shows, as expected, after filtering by a book title in the read shelf.

![image](https://user-images.githubusercontent.com/11173328/85725672-3d4a3800-b6ed-11ea-808f-5449ef9e5107.png)
But the book also shows when other shelves are selected, such as the one in the screenshot above.

**Comment by jcrosswh** [comment]
Hello @knjk04, I'd like to help with this issue, please let me know if I could help on this.

The issue that I see is that the `BooksInShelfView.updateList` method queries for books in the DB if the filter is populated, bypassing the shelf filter.

Design:
Remove the query by filter from the `updateList` method and instead apply the filter to the list of books from `selectedShelf.getBooks()` via a stream.

**Comment by knjk04** [comment]
Thanks, I'll assign you to the issue!

I may have misunderstood you here, but I think the DB is queried both when the filter is populated and when it isn't. I think the issue is with the following code:

```java
if (bookTitle != null && !bookTitle.isEmpty()) {
    LOGGER.log(Level.INFO, "Searching for the filter " + bookTitle);
    bookGrid.setItems(bookService.findAll(bookTitle));
}
```

When the shelf to display is changed, the `bookTitle` variable is not reset to null or the empty string. Consequently, the condition in the `if` is still true. `BookService` is searching for all books in its repository, not for books in a specific shelf. So I think you're right when you said that filtering via a stream on the books from the selected shelf should work.

**Comment by jcrosswh** [comment]
You're correct, there's a query on line 237 to find all books within the shelf, but if the book title filter has also been set, then there's a second query performed on line 240 (which you mentioned) just on the book title and doesn't take into account the selected shelf.  I noticed that the shelf object already has a list of all the books with titles available, so I went ahead and used that information to generate the correct list.

I've submitted the PR with the change - please do let me know there are issues or if there's another way that you'd like to see if solved.

**Comment by knjk04** [comment]
Ah, I understand now. That's correct. 

Thanks, I'll take a look shortly
