### ISSUE TITLE
Sort by author name

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#94]
**Describe the solution you'd like**
Configure the grid in Vaadin (`BookShelfView.java`) to make the author names sortable. A `comparator` may be required. 

For now, the names should be sorted by the first name alphabetically in ascending order (A-Z).

**Additional context**
![image](https://user-images.githubusercontent.com/11173328/85830856-353dd700-b785-11ea-98ba-38ed62ef3553.png)

Currently, it not yet possible to sort the author names.

**Comment by nagasaichaitanya** [comment]
I am interested to take this up. Can this be assigned to me ?

**Comment by knjk04** [comment]
Sure thing. Thanks!
