### ISSUE TITLE
Replace shelf SQL query with findByShelfName

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#95]
In the `PredefinedShelfRepository`, a query, called `search`, is used to return all of the shelves that match the parameter shelf's name.

This could be refactored to use Spring Data JPA's query derivation. 

In simple words, the `PredefinedShelf` entity contains an attribute called `shelfName`. Therefore, Spring Data JPA provides this query for us. It's prefixed with `findBy` followed the by the search criteria. In this case, it's `findByShelfName`.

See [query methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods) in the Spring Data JPA documentation.

**Comment by judeibe** [comment]
I would like to be assigned to this issue.

**Comment by knjk04** [comment]
Thanks!
